// AUTO-GENERATED by scripts/sample-artworks.cjs from https://best-artworks.uwazi.io
// (public Uwazi instance, CC-licensed 'Best Artworks of All Time' dataset).
// A CAPPED sample for exercising image cards against real aspect ratios.
// Do not edit by hand — re-run the script.
import type { Artwork, ArtworkArtist } from "./types";

/** Public path prefix for the sampled images. */
export const ARTWORK_IMAGE_BASE = "/artwork-images";

export const artworks: Artwork[] = [
 {
  "id": "lg6hoh0zxic",
  "title": "Albrecht Dürer 117",
  "artistId": "2fs56od9s5h",
  "artistName": "Albrecht Dürer",
  "genres": [
   "Northern Renaissance"
  ],
  "nationalities": [
   "German"
  ],
  "datasetNumber": 117,
  "image": {
   "file": "16017088903577yrzgj7tzn5.jpg",
   "originalName": "Albrecht_Dürer_117.jpg",
   "bytes": 131434,
   "width": 607,
   "height": 1024,
   "aspect": "portrait"
  }
 },
 {
  "id": "kn424mkj94",
  "title": "Albrecht Dürer 11",
  "artistId": "2fs56od9s5h",
  "artistName": "Albrecht Dürer",
  "genres": [
   "Northern Renaissance"
  ],
  "nationalities": [
   "German"
  ],
  "datasetNumber": 11,
  "image": {
   "file": "1601708883168xwrh429c67.jpg",
   "originalName": "Albrecht_Dürer_11.jpg",
   "bytes": 541193,
   "width": 1678,
   "height": 2048,
   "aspect": "portrait"
  }
 },
 {
  "id": "ytj5os85wd",
  "title": "Albrecht Dürer 110",
  "artistId": "2fs56od9s5h",
  "artistName": "Albrecht Dürer",
  "genres": [
   "Northern Renaissance"
  ],
  "nationalities": [
   "German"
  ],
  "datasetNumber": 110,
  "image": {
   "file": "1601708884040jje6e5b6ba9.jpg",
   "originalName": "Albrecht_Dürer_110.jpg",
   "bytes": 102750,
   "width": 800,
   "height": 553,
   "aspect": "landscape"
  }
 },
 {
  "id": "zcnacjtz4sk",
  "title": "Alfred Sisley 173",
  "artistId": "ej6lkcc5mz",
  "artistName": "Alfred Sisley",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French",
   "British"
  ],
  "datasetNumber": 173,
  "image": {
   "file": "1601709225014emqjjktej9u.jpg",
   "originalName": "Alfred_Sisley_173.jpg",
   "bytes": 512307,
   "width": 2560,
   "height": 1758,
   "aspect": "landscape"
  }
 },
 {
  "id": "r0b6ov9ghhh",
  "title": "Alfred Sisley 167",
  "artistId": "ej6lkcc5mz",
  "artistName": "Alfred Sisley",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French",
   "British"
  ],
  "datasetNumber": 167,
  "image": {
   "file": "16017092192279ds46ewybxb.jpg",
   "originalName": "Alfred_Sisley_167.jpg",
   "bytes": 307946,
   "width": 1280,
   "height": 881,
   "aspect": "landscape"
  }
 },
 {
  "id": "3ml271lew83",
  "title": "Alfred Sisley 175",
  "artistId": "ej6lkcc5mz",
  "artistName": "Alfred Sisley",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French",
   "British"
  ],
  "datasetNumber": 175,
  "image": {
   "file": "1601709226715erzy3hmz095.jpg",
   "originalName": "Alfred_Sisley_175.jpg",
   "bytes": 134757,
   "width": 1024,
   "height": 809,
   "aspect": "landscape"
  }
 },
 {
  "id": "j5jptzyfcuc",
  "title": "Amedeo Modigliani 101",
  "artistId": "6lg4fsrtzeu",
  "artistName": "Amedeo Modigliani",
  "genres": [
   "Expressionism"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 101,
  "image": {
   "file": "1601709376198gwrg5tn723h.jpg",
   "originalName": "Amedeo_Modigliani_101.jpg",
   "bytes": 23016,
   "width": 477,
   "height": 805,
   "aspect": "portrait"
  }
 },
 {
  "id": "a1xuzgebfsg",
  "title": "Amedeo Modigliani 102",
  "artistId": "6lg4fsrtzeu",
  "artistName": "Amedeo Modigliani",
  "genres": [
   "Expressionism"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 102,
  "image": {
   "file": "160170937695633ptqzl20us.jpg",
   "originalName": "Amedeo_Modigliani_102.jpg",
   "bytes": 120943,
   "width": 444,
   "height": 807,
   "aspect": "portrait"
  }
 },
 {
  "id": "qhgxs8xcf8k",
  "title": "Amedeo Modigliani 103",
  "artistId": "6lg4fsrtzeu",
  "artistName": "Amedeo Modigliani",
  "genres": [
   "Expressionism"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 103,
  "image": {
   "file": "160170937771599mhhybukq.jpg",
   "originalName": "Amedeo_Modigliani_103.jpg",
   "bytes": 41627,
   "width": 517,
   "height": 800,
   "aspect": "portrait"
  }
 },
 {
  "id": "rjt45pcfg4",
  "title": "Andrei Rublev 55",
  "artistId": "bovvez624s9",
  "artistName": "Andrei Rublev",
  "genres": [
   "Byzantine Art"
  ],
  "nationalities": [
   "Russian"
  ],
  "datasetNumber": 55,
  "image": {
   "file": "16017095752076x78lppa1yt.jpg",
   "originalName": "Andrei_Rublev_55.jpg",
   "bytes": 133672,
   "width": 699,
   "height": 653,
   "aspect": "landscape"
  }
 },
 {
  "id": "l1sw5rqcoy9",
  "title": "Andy Warhol 181",
  "artistId": "njkbd37j20s",
  "artistName": "Andy Warhol",
  "genres": [
   "Pop Art"
  ],
  "nationalities": [
   "American"
  ],
  "datasetNumber": 181,
  "image": {
   "file": "1601709684104t5bsuq16aa.jpg",
   "originalName": "Andy_Warhol_181.jpg",
   "bytes": 50528,
   "width": 479,
   "height": 480,
   "aspect": "square"
  }
 },
 {
  "id": "jn7zpv5ndh",
  "title": "Andy Warhol 18",
  "artistId": "njkbd37j20s",
  "artistName": "Andy Warhol",
  "genres": [
   "Pop Art"
  ],
  "nationalities": [
   "American"
  ],
  "datasetNumber": 18,
  "image": {
   "file": "1601709682638q6r8kghv7tg.jpg",
   "originalName": "Andy_Warhol_18.jpg",
   "bytes": 98104,
   "width": 430,
   "height": 452,
   "aspect": "square"
  }
 },
 {
  "id": "vxj0p6peve",
  "title": "Andy Warhol 54",
  "artistId": "njkbd37j20s",
  "artistName": "Andy Warhol",
  "genres": [
   "Pop Art"
  ],
  "nationalities": [
   "American"
  ],
  "datasetNumber": 54,
  "image": {
   "file": "1601709713464hoixlcql2r4.jpg",
   "originalName": "Andy_Warhol_54.jpg",
   "bytes": 38297,
   "width": 510,
   "height": 508,
   "aspect": "square"
  }
 },
 {
  "id": "0emkd3voudi",
  "title": "Camille Pissarro 1",
  "artistId": "usoj4xswzo",
  "artistName": "Camille Pissarro",
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 1,
  "image": {
   "file": "1601709753788rfufkpu3gqs.jpg",
   "originalName": "Camille_Pissarro_1.jpg",
   "bytes": 352424,
   "width": 1225,
   "height": 1023,
   "aspect": "landscape"
  }
 },
 {
  "id": "0b5k9vxrkcf8",
  "title": "Camille Pissarro 10",
  "artistId": "usoj4xswzo",
  "artistName": "Camille Pissarro",
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 10,
  "image": {
   "file": "160170975450750w4g3bguhv.jpg",
   "originalName": "Camille_Pissarro_10.jpg",
   "bytes": 225367,
   "width": 1280,
   "height": 828,
   "aspect": "landscape"
  }
 },
 {
  "id": "j7ap6bw6eme",
  "title": "Camille Pissarro 24",
  "artistId": "usoj4xswzo",
  "artistName": "Camille Pissarro",
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 24,
  "image": {
   "file": "160170976537060sv13pjjij.jpg",
   "originalName": "Camille_Pissarro_24.jpg",
   "bytes": 307654,
   "width": 1224,
   "height": 1024,
   "aspect": "landscape"
  }
 },
 {
  "id": "iw60r3ma72",
  "title": "Caravaggio 18",
  "artistId": "srz34fuaoxn",
  "artistName": "Caravaggio",
  "genres": [
   "Baroque"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 18,
  "image": {
   "file": "1601709827618vihffvymee9.jpg",
   "originalName": "Caravaggio_18.jpg",
   "bytes": 158012,
   "width": 1315,
   "height": 976,
   "aspect": "landscape"
  }
 },
 {
  "id": "kd3tg9kjfr",
  "title": "Caravaggio 1",
  "artistId": "srz34fuaoxn",
  "artistName": "Caravaggio",
  "genres": [
   "Baroque"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 1,
  "image": {
   "file": "1601709821016x95g12n9xd.jpg",
   "originalName": "Caravaggio_1.jpg",
   "bytes": 92612,
   "width": 691,
   "height": 1000,
   "aspect": "portrait"
  }
 },
 {
  "id": "mhrdck1khwe",
  "title": "Caravaggio 10",
  "artistId": "srz34fuaoxn",
  "artistName": "Caravaggio",
  "genres": [
   "Baroque"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 10,
  "image": {
   "file": "1601709821761adm6fgytlqv.jpg",
   "originalName": "Caravaggio_10.jpg",
   "bytes": 194140,
   "width": 2024,
   "height": 1513,
   "aspect": "landscape"
  }
 },
 {
  "id": "urbjhgvdnsl",
  "title": "Claude Monet 13",
  "artistId": "f6cbqhfwynn",
  "artistName": "Claude Monet",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 13,
  "image": {
   "file": "1601709863244o7cwsz78y2.jpg",
   "originalName": "Claude_Monet_13.jpg",
   "bytes": 293188,
   "width": 1000,
   "height": 1366,
   "aspect": "portrait"
  }
 },
 {
  "id": "r6wa0a7ht7p",
  "title": "Claude Monet 14",
  "artistId": "f6cbqhfwynn",
  "artistName": "Claude Monet",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 14,
  "image": {
   "file": "1601709863952ay2ddxrmdpp.jpg",
   "originalName": "Claude_Monet_14.jpg",
   "bytes": 280968,
   "width": 1024,
   "height": 1032,
   "aspect": "square"
  }
 },
 {
  "id": "va32k2y40ds",
  "title": "Claude Monet 1",
  "artistId": "f6cbqhfwynn",
  "artistName": "Claude Monet",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 1,
  "image": {
   "file": "1601709860422xg4r8pdfiv.jpg",
   "originalName": "Claude_Monet_1.jpg",
   "bytes": 312580,
   "width": 1024,
   "height": 791,
   "aspect": "landscape"
  }
 },
 {
  "id": "735q85jkvo7",
  "title": "Diego Rivera 29",
  "artistId": "pdxgzc5hw",
  "artistName": "Diego Rivera",
  "genres": [
   "Social Realism",
   "Muralism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "datasetNumber": 29,
  "image": {
   "file": "16017099284231few6kocxgj.jpg",
   "originalName": "Diego_Rivera_29.jpg",
   "bytes": 103743,
   "width": 640,
   "height": 800,
   "aspect": "portrait"
  }
 },
 {
  "id": "t64h3b1347",
  "title": "Diego Rivera 3",
  "artistId": "pdxgzc5hw",
  "artistName": "Diego Rivera",
  "genres": [
   "Social Realism",
   "Muralism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "datasetNumber": 3,
  "image": {
   "file": "16017099291233xmos1m530m.jpg",
   "originalName": "Diego_Rivera_3.jpg",
   "bytes": 133009,
   "width": 800,
   "height": 605,
   "aspect": "landscape"
  }
 },
 {
  "id": "jnudvk74p4",
  "title": "Diego Rivera 30",
  "artistId": "pdxgzc5hw",
  "artistName": "Diego Rivera",
  "genres": [
   "Social Realism",
   "Muralism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "datasetNumber": 30,
  "image": {
   "file": "1601709929885737sxdw0ub4.jpg",
   "originalName": "Diego_Rivera_30.jpg",
   "bytes": 192899,
   "width": 800,
   "height": 791,
   "aspect": "square"
  }
 },
 {
  "id": "uhek1jjvjmn",
  "title": "Diego Velazquez 20",
  "artistId": "gvdk2ab7d24",
  "artistName": "Diego Velazquez",
  "genres": [
   "Baroque"
  ],
  "nationalities": [
   "Spanish"
  ],
  "datasetNumber": 20,
  "image": {
   "file": "1601709991454uezfp5uho8.jpg",
   "originalName": "Diego_Velazquez_20.jpg",
   "bytes": 104025,
   "width": 780,
   "height": 1000,
   "aspect": "portrait"
  }
 },
 {
  "id": "mf6p3n7bl2h",
  "title": "Diego Velazquez 39",
  "artistId": "gvdk2ab7d24",
  "artistName": "Diego Velazquez",
  "genres": [
   "Baroque"
  ],
  "nationalities": [
   "Spanish"
  ],
  "datasetNumber": 39,
  "image": {
   "file": "160171000547471zh6ceo9ul.jpg",
   "originalName": "Diego_Velazquez_39.jpg",
   "bytes": 119127,
   "width": 676,
   "height": 864,
   "aspect": "portrait"
  }
 },
 {
  "id": "qo6me29afy",
  "title": "Edgar Degas 12",
  "artistId": "4tk4z925v9c",
  "artistName": "Edgar Degas",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 12,
  "image": {
   "file": "1601710067813ienmiftsni.jpg",
   "originalName": "Edgar_Degas_12.jpg",
   "bytes": 279402,
   "width": 2093,
   "height": 1487,
   "aspect": "landscape"
  }
 },
 {
  "id": "l61fnv5uomm",
  "title": "Edgar Degas 118",
  "artistId": "4tk4z925v9c",
  "artistName": "Edgar Degas",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 118,
  "image": {
   "file": "16017100664430u36z0blplrq.jpg",
   "originalName": "Edgar_Degas_118.jpg",
   "bytes": 241589,
   "width": 744,
   "height": 1104,
   "aspect": "portrait"
  }
 },
 {
  "id": "0izblwszp4t",
  "title": "Edgar Degas 119",
  "artistId": "4tk4z925v9c",
  "artistName": "Edgar Degas",
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 119,
  "image": {
   "file": "1601710067108wtl93dbq9u.jpg",
   "originalName": "Edgar_Degas_119.jpg",
   "bytes": 254065,
   "width": 1846,
   "height": 1479,
   "aspect": "landscape"
  }
 },
 {
  "id": "p5fwel3bt6a",
  "title": "Edouard Manet 1",
  "artistId": "2bwv4xtw3dr",
  "artistName": "Edouard Manet",
  "genres": [
   "Impressionism",
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 1,
  "image": {
   "file": "1601710517313s1126np8y9.jpg",
   "originalName": "Edouard_Manet_1.jpg",
   "bytes": 193417,
   "width": 1009,
   "height": 838,
   "aspect": "landscape"
  }
 },
 {
  "id": "jits2uas6zr",
  "title": "Edouard Manet 2",
  "artistId": "2bwv4xtw3dr",
  "artistName": "Edouard Manet",
  "genres": [
   "Impressionism",
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 2,
  "image": {
   "file": "1601710524213532rw04h8f.jpg",
   "originalName": "Edouard_Manet_2.jpg",
   "bytes": 145031,
   "width": 928,
   "height": 1129,
   "aspect": "portrait"
  }
 },
 {
  "id": "nxbm2k057h",
  "title": "Edouard Manet 20",
  "artistId": "2bwv4xtw3dr",
  "artistName": "Edouard Manet",
  "genres": [
   "Impressionism",
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 20,
  "image": {
   "file": "16017105248356ros8z0bal2.jpg",
   "originalName": "Edouard_Manet_20.jpg",
   "bytes": 214535,
   "width": 1249,
   "height": 783,
   "aspect": "landscape"
  }
 },
 {
  "id": "dboou4jx0w9",
  "title": "Edvard Munch 29",
  "artistId": "j3f21rbl0ee",
  "artistName": "Edvard Munch",
  "genres": [
   "Expressionism",
   "Symbolism"
  ],
  "nationalities": [
   "Norwegian"
  ],
  "datasetNumber": 29,
  "image": {
   "file": "16017105867996aui0kam63e.jpg",
   "originalName": "Edvard_Munch_29.jpg",
   "bytes": 424162,
   "width": 1258,
   "height": 1024,
   "aspect": "landscape"
  }
 },
 {
  "id": "56iibh696j6",
  "title": "Edvard Munch 41",
  "artistId": "j3f21rbl0ee",
  "artistName": "Edvard Munch",
  "genres": [
   "Expressionism",
   "Symbolism"
  ],
  "nationalities": [
   "Norwegian"
  ],
  "datasetNumber": 41,
  "image": {
   "file": "1601710595323nc3qu2901vn.jpg",
   "originalName": "Edvard_Munch_41.jpg",
   "bytes": 135940,
   "width": 708,
   "height": 800,
   "aspect": "portrait"
  }
 },
 {
  "id": "ci6umlqngkw",
  "title": "Edvard Munch 42",
  "artistId": "j3f21rbl0ee",
  "artistName": "Edvard Munch",
  "genres": [
   "Expressionism",
   "Symbolism"
  ],
  "nationalities": [
   "Norwegian"
  ],
  "datasetNumber": 42,
  "image": {
   "file": "1601710595928a3fnx9asseb.jpg",
   "originalName": "Edvard_Munch_42.jpg",
   "bytes": 255993,
   "width": 749,
   "height": 1024,
   "aspect": "portrait"
  }
 },
 {
  "id": "5ehudvpwvn6",
  "title": "El Greco 22",
  "artistId": "07vu3w2gl7kj",
  "artistName": "El Greco",
  "genres": [
   "Mannerism"
  ],
  "nationalities": [
   "Spanish",
   "Greek"
  ],
  "datasetNumber": 22,
  "image": {
   "file": "1601710623698pwaox1ual4.jpg",
   "originalName": "El_Greco_22.jpg",
   "bytes": 149714,
   "width": 509,
   "height": 807,
   "aspect": "portrait"
  }
 },
 {
  "id": "z37xg96wzv8",
  "title": "El Greco 23",
  "artistId": "07vu3w2gl7kj",
  "artistName": "El Greco",
  "genres": [
   "Mannerism"
  ],
  "nationalities": [
   "Spanish",
   "Greek"
  ],
  "datasetNumber": 23,
  "image": {
   "file": "1601710624322mi1f3sifme.jpg",
   "originalName": "El_Greco_23.jpg",
   "bytes": 149894,
   "width": 646,
   "height": 807,
   "aspect": "portrait"
  }
 },
 {
  "id": "ilx4q8i5se",
  "title": "El Greco 24",
  "artistId": "07vu3w2gl7kj",
  "artistName": "El Greco",
  "genres": [
   "Mannerism"
  ],
  "nationalities": [
   "Spanish",
   "Greek"
  ],
  "datasetNumber": 24,
  "image": {
   "file": "1601710624931wn3akqaclmf.jpg",
   "originalName": "El_Greco_24.jpg",
   "bytes": 152028,
   "width": 807,
   "height": 591,
   "aspect": "landscape"
  }
 },
 {
  "id": "12nf64p1d4o",
  "title": "Francisco Goya 113",
  "artistId": "tfg8yubj8ii",
  "artistName": "Francisco Goya",
  "genres": [
   "Romanticism"
  ],
  "nationalities": [
   "Spanish"
  ],
  "datasetNumber": 113,
  "image": {
   "file": "1601710696977kul3fk8uga.jpg",
   "originalName": "Francisco_Goya_113.jpg",
   "bytes": 126430,
   "width": 669,
   "height": 984,
   "aspect": "portrait"
  }
 },
 {
  "id": "hnzyghlk1ra",
  "title": "Francisco Goya 114",
  "artistId": "tfg8yubj8ii",
  "artistName": "Francisco Goya",
  "genres": [
   "Romanticism"
  ],
  "nationalities": [
   "Spanish"
  ],
  "datasetNumber": 114,
  "image": {
   "file": "1601710697571dfgx52117eb.jpg",
   "originalName": "Francisco_Goya_114.jpg",
   "bytes": 182902,
   "width": 573,
   "height": 758,
   "aspect": "portrait"
  }
 },
 {
  "id": "l4hynsz3sfg",
  "title": "Francisco Goya 186",
  "artistId": "tfg8yubj8ii",
  "artistName": "Francisco Goya",
  "genres": [
   "Romanticism"
  ],
  "nationalities": [
   "Spanish"
  ],
  "datasetNumber": 186,
  "image": {
   "file": "1601710745117w8455idl3hq.jpg",
   "originalName": "Francisco_Goya_186.jpg",
   "bytes": 150066,
   "width": 1000,
   "height": 1350,
   "aspect": "portrait"
  }
 },
 {
  "id": "thw01iwh0e",
  "title": "Frida Kahlo 108",
  "artistId": "1ey7gxt3i39",
  "artistName": "Frida Kahlo",
  "genres": [
   "Surrealism",
   "Primitivism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "datasetNumber": 108,
  "image": {
   "file": "1601710865372u4yu4pn32sq.jpg",
   "originalName": "Frida_Kahlo_108.jpg",
   "bytes": 159467,
   "width": 591,
   "height": 807,
   "aspect": "portrait"
  }
 },
 {
  "id": "687bmvpel77",
  "title": "Frida Kahlo 109",
  "artistId": "1ey7gxt3i39",
  "artistName": "Frida Kahlo",
  "genres": [
   "Surrealism",
   "Primitivism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "datasetNumber": 109,
  "image": {
   "file": "160171086595153geuetxbrc.jpg",
   "originalName": "Frida_Kahlo_109.jpg",
   "bytes": 172050,
   "width": 586,
   "height": 807,
   "aspect": "portrait"
  }
 },
 {
  "id": "a0qilflb7bc",
  "title": "Frida Kahlo 11",
  "artistId": "1ey7gxt3i39",
  "artistName": "Frida Kahlo",
  "genres": [
   "Surrealism",
   "Primitivism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "datasetNumber": 11,
  "image": {
   "file": "1601710866515m7qanfnanvl.jpg",
   "originalName": "Frida_Kahlo_11.jpg",
   "bytes": 157747,
   "width": 739,
   "height": 807,
   "aspect": "portrait"
  }
 },
 {
  "id": "4s55mszinra",
  "title": "Georges Seurat 41",
  "artistId": "qiozg3v7r6d",
  "artistName": "Georges Seurat",
  "genres": [
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 41,
  "image": {
   "file": "1601710947528u1lyskp5tc.jpg",
   "originalName": "Georges_Seurat_41.jpg",
   "bytes": 41877,
   "width": 390,
   "height": 480,
   "aspect": "portrait"
  }
 },
 {
  "id": "6mzouiclg8p",
  "title": "Georges Seurat 42",
  "artistId": "qiozg3v7r6d",
  "artistName": "Georges Seurat",
  "genres": [
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 42,
  "image": {
   "file": "160171094810772t7fq3liva.jpg",
   "originalName": "Georges_Seurat_42.jpg",
   "bytes": 50522,
   "width": 400,
   "height": 480,
   "aspect": "portrait"
  }
 },
 {
  "id": "nivrlot2rn",
  "title": "Georges Seurat 37",
  "artistId": "qiozg3v7r6d",
  "artistName": "Georges Seurat",
  "genres": [
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 37,
  "image": {
   "file": "1601710944712zh7fct8i39.jpg",
   "originalName": "Georges_Seurat_37.jpg",
   "bytes": 39323,
   "width": 368,
   "height": 480,
   "aspect": "portrait"
  }
 },
 {
  "id": "x2p6jcbjtq",
  "title": "Giotto di Bondone 66",
  "artistId": "rhi5sf0wwni",
  "artistName": "Giotto di Bondone",
  "genres": [
   "Proto Renaissance"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 66,
  "image": {
   "file": "1601710997774s71x4rp5bnl.jpg",
   "originalName": "Giotto_di_Bondone_66.jpg",
   "bytes": 162069,
   "width": 1000,
   "height": 911,
   "aspect": "landscape"
  }
 },
 {
  "id": "xdedwrfec0l",
  "title": "Giotto di Bondone 93",
  "artistId": "rhi5sf0wwni",
  "artistName": "Giotto di Bondone",
  "genres": [
   "Proto Renaissance"
  ],
  "nationalities": [
   "Italian"
  ],
  "datasetNumber": 93,
  "image": {
   "file": "160171101453325i35qxtknv.jpg",
   "originalName": "Giotto_di_Bondone_93.jpg",
   "bytes": 188988,
   "width": 860,
   "height": 900,
   "aspect": "square"
  }
 },
 {
  "id": "62lslz95eyk",
  "title": "Gustav Klimt 41",
  "artistId": "euknzfajgpm",
  "artistName": "Gustav Klimt",
  "genres": [
   "Symbolism",
   "Art Nouveau"
  ],
  "nationalities": [
   "Austrian"
  ],
  "datasetNumber": 41,
  "image": {
   "file": "1601711047880w97iysatxch.jpg",
   "originalName": "Gustav_Klimt_41.jpg",
   "bytes": 229592,
   "width": 1419,
   "height": 2048,
   "aspect": "portrait"
  }
 },
 {
  "id": "sg3vqizm0se",
  "title": "Gustav Klimt 42",
  "artistId": "euknzfajgpm",
  "artistName": "Gustav Klimt",
  "genres": [
   "Symbolism",
   "Art Nouveau"
  ],
  "nationalities": [
   "Austrian"
  ],
  "datasetNumber": 42,
  "image": {
   "file": "1601711048412ow7rgkw5t3e.jpg",
   "originalName": "Gustav_Klimt_42.jpg",
   "bytes": 309261,
   "width": 1024,
   "height": 1033,
   "aspect": "square"
  }
 },
 {
  "id": "r4bjx0elg3",
  "title": "Gustav Klimt 43",
  "artistId": "euknzfajgpm",
  "artistName": "Gustav Klimt",
  "genres": [
   "Symbolism",
   "Art Nouveau"
  ],
  "nationalities": [
   "Austrian"
  ],
  "datasetNumber": 43,
  "image": {
   "file": "1601711048979wfh79mjjnss.jpg",
   "originalName": "Gustav_Klimt_43.jpg",
   "bytes": 540403,
   "width": 2024,
   "height": 2032,
   "aspect": "square"
  }
 },
 {
  "id": "j17n8x9c3",
  "title": "Gustave Courbet 51",
  "artistId": "wblyfqs2luh",
  "artistName": "Gustave Courbet",
  "genres": [
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 51,
  "image": {
   "file": "16017111076832w8wz1dzqlg.jpg",
   "originalName": "Gustave_Courbet_51.jpg",
   "bytes": 129984,
   "width": 800,
   "height": 638,
   "aspect": "landscape"
  }
 },
 {
  "id": "id6thbqot9e",
  "title": "Gustave Courbet 8",
  "artistId": "wblyfqs2luh",
  "artistName": "Gustave Courbet",
  "genres": [
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 8,
  "image": {
   "file": "1601711113506lb4pyacdctf.jpg",
   "originalName": "Gustave_Courbet_8.jpg",
   "bytes": 84390,
   "width": 800,
   "height": 584,
   "aspect": "landscape"
  }
 },
 {
  "id": "84fywfbozm8",
  "title": "Gustave Courbet 9",
  "artistId": "wblyfqs2luh",
  "artistName": "Gustave Courbet",
  "genres": [
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 9,
  "image": {
   "file": "1601711114062sfh51stxdy.jpg",
   "originalName": "Gustave_Courbet_9.jpg",
   "bytes": 227697,
   "width": 1130,
   "height": 921,
   "aspect": "landscape"
  }
 },
 {
  "id": "olr7wxnpadk",
  "title": "Henri Matisse 1",
  "artistId": "2jkq3il36x",
  "artistName": "Henri Matisse",
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 1,
  "image": {
   "file": "1601711114596d6dzig1wg8t.jpg",
   "originalName": "Henri_Matisse_1.jpg",
   "bytes": 52350,
   "width": 581,
   "height": 721,
   "aspect": "portrait"
  }
 },
 {
  "id": "exffbxcppb7",
  "title": "Henri Matisse 100",
  "artistId": "2jkq3il36x",
  "artistName": "Henri Matisse",
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 100,
  "image": {
   "file": "16017111156456szawrc6hv.jpg",
   "originalName": "Henri_Matisse_100.jpg",
   "bytes": 42302,
   "width": 569,
   "height": 719,
   "aspect": "portrait"
  }
 },
 {
  "id": "25j4i07lug4",
  "title": "Henri Matisse 101",
  "artistId": "2jkq3il36x",
  "artistName": "Henri Matisse",
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 101,
  "image": {
   "file": "1601711116183nvdud6p38rg.jpg",
   "originalName": "Henri_Matisse_101.jpg",
   "bytes": 37952,
   "width": 521,
   "height": 823,
   "aspect": "portrait"
  }
 },
 {
  "id": "rn288y5gfc",
  "title": "Henri Rousseau 29",
  "artistId": "g2d4n0z2xeb",
  "artistName": "Henri Rousseau",
  "genres": [
   "Primitivism"
  ],
  "nationalities": [
   "French"
  ],
  "datasetNumber": 29,
  "image": {
   "file": "1601711223364fg2ujsc3g9k.jpg",
   "originalName": "Henri_Rousseau_29.jpg",
   "bytes": 68113,
   "width": 560,
   "height": 750,
   "aspect": "portrait"
  }
 }
];

export const artworkArtists: ArtworkArtist[] = [
 {
  "id": "2fs56od9s5h",
  "name": "Albrecht Dürer",
  "bornYear": 1471,
  "diedYear": 1528,
  "genres": [
   "Northern Renaissance"
  ],
  "nationalities": [
   "German"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Albrecht_Dürer",
  "paintings": 328
 },
 {
  "id": "ej6lkcc5mz",
  "name": "Alfred Sisley",
  "bornYear": 1839,
  "diedYear": 1899,
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French",
   "British"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Alfred_Sisley",
  "paintings": 259
 },
 {
  "id": "6lg4fsrtzeu",
  "name": "Amedeo Modigliani",
  "bornYear": 1884,
  "diedYear": 1920,
  "genres": [
   "Expressionism"
  ],
  "nationalities": [
   "Italian"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Amedeo_Modigliani",
  "paintings": 193
 },
 {
  "id": "bovvez624s9",
  "name": "Andrei Rublev",
  "bornYear": 1360,
  "diedYear": 1430,
  "genres": [
   "Byzantine Art"
  ],
  "nationalities": [
   "Russian"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Andrei_Rublev",
  "paintings": 99
 },
 {
  "id": "njkbd37j20s",
  "name": "Andy Warhol",
  "bornYear": 1928,
  "diedYear": 1987,
  "genres": [
   "Pop Art"
  ],
  "nationalities": [
   "American"
  ],
  "wikipedia": "https://en.wikipedia.org/wiki/Andy_Warhol",
  "paintings": 181
 },
 {
  "id": "usoj4xswzo",
  "name": "Camille Pissarro",
  "bornYear": 1830,
  "diedYear": 1903,
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "https://en.wikipedia.org/wiki/Camille_Pissarro",
  "paintings": 91
 },
 {
  "id": "srz34fuaoxn",
  "name": "Caravaggio",
  "bornYear": 1571,
  "diedYear": 1610,
  "genres": [
   "Baroque"
  ],
  "nationalities": [
   "Italian"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Caravaggio",
  "paintings": 55
 },
 {
  "id": "f6cbqhfwynn",
  "name": "Claude Monet",
  "bornYear": 1840,
  "diedYear": 1926,
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Claude_Monet",
  "paintings": 73
 },
 {
  "id": "pdxgzc5hw",
  "name": "Diego Rivera",
  "bornYear": 1886,
  "diedYear": 1957,
  "genres": [
   "Social Realism",
   "Muralism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Diego_Rivera",
  "paintings": 70
 },
 {
  "id": "gvdk2ab7d24",
  "name": "Diego Velazquez",
  "bornYear": 1599,
  "diedYear": 1660,
  "genres": [
   "Baroque"
  ],
  "nationalities": [
   "Spanish"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Diego_Velázquez",
  "paintings": 129
 },
 {
  "id": "4tk4z925v9c",
  "name": "Edgar Degas",
  "bornYear": 1834,
  "diedYear": 1917,
  "genres": [
   "Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Edgar_Degas",
  "paintings": 702
 },
 {
  "id": "2bwv4xtw3dr",
  "name": "Edouard Manet",
  "bornYear": 1832,
  "diedYear": 1883,
  "genres": [
   "Impressionism",
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Édouard_Manet",
  "paintings": 90
 },
 {
  "id": "j3f21rbl0ee",
  "name": "Edvard Munch",
  "bornYear": 1863,
  "diedYear": 1944,
  "genres": [
   "Expressionism",
   "Symbolism"
  ],
  "nationalities": [
   "Norwegian"
  ],
  "wikipedia": "https://en.wikipedia.org/wiki/Edvard_Munch",
  "paintings": 67
 },
 {
  "id": "07vu3w2gl7kj",
  "name": "El Greco",
  "bornYear": 1541,
  "diedYear": 1614,
  "genres": [
   "Mannerism"
  ],
  "nationalities": [
   "Spanish",
   "Greek"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/El_Greco",
  "paintings": 87
 },
 {
  "id": "tfg8yubj8ii",
  "name": "Francisco Goya",
  "bornYear": 1746,
  "diedYear": 1828,
  "genres": [
   "Romanticism"
  ],
  "nationalities": [
   "Spanish"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Francisco_Goya",
  "paintings": 291
 },
 {
  "id": "1ey7gxt3i39",
  "name": "Frida Kahlo",
  "bornYear": 1907,
  "diedYear": 1954,
  "genres": [
   "Surrealism",
   "Primitivism"
  ],
  "nationalities": [
   "Mexican"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Frida_Kahlo",
  "paintings": 120
 },
 {
  "id": "qiozg3v7r6d",
  "name": "Georges Seurat",
  "bornYear": 1859,
  "diedYear": 1891,
  "genres": [
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "https://en.wikipedia.org/wiki/Georges_Seurat",
  "paintings": 43
 },
 {
  "id": "rhi5sf0wwni",
  "name": "Giotto di Bondone",
  "bornYear": 1266,
  "diedYear": 1337,
  "genres": [
   "Proto Renaissance"
  ],
  "nationalities": [
   "Italian"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Giotto_di_Bondone",
  "paintings": 119
 },
 {
  "id": "euknzfajgpm",
  "name": "Gustav Klimt",
  "bornYear": 1862,
  "diedYear": 1918,
  "genres": [
   "Symbolism",
   "Art Nouveau"
  ],
  "nationalities": [
   "Austrian"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Gustav_Klimt",
  "paintings": 118
 },
 {
  "id": "wblyfqs2luh",
  "name": "Gustave Courbet",
  "bornYear": 1819,
  "diedYear": 1877,
  "genres": [
   "Realism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "https://en.wikipedia.org/wiki/Gustave_Courbet",
  "paintings": 59
 },
 {
  "id": "2jkq3il36x",
  "name": "Henri Matisse",
  "bornYear": 1869,
  "diedYear": 1954,
  "genres": [
   "Impressionism",
   "Post-Impressionism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "http://en.wikipedia.org/wiki/Henri_Matisse",
  "paintings": 186
 },
 {
  "id": "g2d4n0z2xeb",
  "name": "Henri Rousseau",
  "bornYear": 1844,
  "diedYear": 1910,
  "genres": [
   "Primitivism"
  ],
  "nationalities": [
   "French"
  ],
  "wikipedia": "https://en.wikipedia.org/wiki/Henri_Rousseau",
  "paintings": 70
 }
];

/** Shape of the sample, so a consumer can assert coverage rather than hope. */
export const artworkStats = {
 "artworks": 60,
 "artists": 22,
 "byAspect": {
  "portrait": 30,
  "landscape": 22,
  "square": 8
 },
 "imageBytes": 10855577,
 "widest": 1.59514687100894,
 "tallest": 0.550185873605948
} as const;
