// AUTO-GENERATED by scripts/sample-artworks.cjs from https://best-artworks.uwazi.io
// (public Uwazi instance, CC-licensed 'Best Artworks of All Time' dataset).
// A CAPPED sample for exercising image cards against real aspect ratios.
// Do not edit by hand — re-run the script.
export * from "./types";
export * from "./artworks";
