// AUTO-GENERATED by scripts/sample-artworks.cjs from https://best-artworks.uwazi.io
// (public Uwazi instance, CC-licensed 'Best Artworks of All Time' dataset).
// A CAPPED sample for exercising image cards against real aspect ratios.
// Do not edit by hand — re-run the script.

/** Intrinsic geometry of a sampled painting, read from the JPEG itself. */
export interface ArtworkImage {
  /** File under public/artwork-images. */
  file: string;
  originalName: string;
  bytes: number;
  width: number;
  height: number;
  /** Derived from the real dimensions — the reason this corpus exists. */
  aspect: "portrait" | "landscape" | "square";
}

export interface Artwork {
  id: string;
  title: string;
  artistId: string | null;
  artistName: string | null;
  genres: string[];
  nationalities: string[];
  datasetNumber: number | null;
  image: ArtworkImage;
}

export interface ArtworkArtist {
  id: string;
  name: string;
  bornYear: number | null;
  diedYear: number | null;
  genres: string[];
  nationalities: string[];
  wikipedia: string | null;
  paintings: number | null;
}
