// AUTO-GENERATED by scripts/import-cejil.cjs from the CEJIL dump. Do not edit by hand.
// Public sample: published, non-permissioned records from summa.cejil.org.
export * from "./types";
export { cejilTemplates } from "./templates";
export { cejilThesauri } from "./thesauri";
export { cejilRelationTypes } from "./relationTypes";
export { cejilSettings } from "./settings";
export { cejilEntities } from "./entities";
export { cejilRelationships } from "./relationships";
export { cejilFiles } from "./files";
export { cejilFullText } from "./fullText";

export const cejilManifest = {"cases":30,"entities":1338,"sharedEntities":446,"relationships":888,"files":483,"pdfs":30,"fullTextDocs":30};
