// AUTO-GENERATED by scripts/import-cejil.cjs from the CEJIL dump. Do not edit by hand.
// Full published corpus from summa.cejil.org (the heavy entity/relationship/file/
// fullText data lives as JSON under public/cejil-data, lazy-loaded at runtime).
export * from "./types";
export { cejilTemplates } from "./templates";
export { cejilThesauri } from "./thesauri";
export { cejilRelationTypes } from "./relationTypes";
export { cejilSettings } from "./settings";
export { cejilMenu } from "./menu";
export { cejilPages } from "./pages";
export { cejilEntityCountByTemplate, cejilUsageByRelationType, cejilStats } from "./aggregates";

export const cejilManifest = {"cases":423,"sharedEntities":4398,"menu":6,"pages":6,"entities":4398,"entityDocs":13194,"relationships":16998,"files":5245,"pdfs":80,"fullTextDocs":80,"templates":19,"thesauri":8,"relationTypes":17,"languages":3};
