// AUTO-GENERATED by scripts/import-cejil.cjs from the CEJIL dump. Do not edit by hand.
// Full published corpus from summa.cejil.org (the heavy entity/relationship/file/
// fullText data lives as JSON under public/cejil-data, lazy-loaded at runtime).
import type { CejilPage } from "./types";
export const cejilPages: CejilPage[] = [{"id":"58b2f3a45d59f31e1345b896","title":"Jueces","slug":"59hhexlzlpthf8gi8gerd4pldi","published":true},{"id":"58b2f3a45d59f31e1345b89c","title":"Old - Inicio","slug":"dicxg0oagy3xgr7ixef80k9","published":true},{"id":"58b2f3a45d59f31e1345b8a2","title":"Tabla de ratificaciones: Convención Americana sobre Derechos Humanos","slug":"f0r93hzwbys4zhdsrg4qs38fr","published":true},{"id":"5cb72d02abf8cf3ac23d54e7","title":"Inicio","slug":"dipkmkm5uwm","published":true},{"id":"5d07f5f2fb1d211f0fa6d411","title":"Contacto","slug":"3suo4v3lrc7","published":true},{"id":"5d6d33d824894a0aa6978eb7","title":"Instrutivo","slug":"lxxazp0lj6s","published":true}];
