// AUTO-GENERATED by scripts/import-cejil.cjs from the CEJIL dump. Do not edit by hand.
// Public sample: published, non-permissioned records from summa.cejil.org.
import type { CejilSettings } from "./types";
export const cejilSettings: CejilSettings = {"siteName":"CEJIL","defaultLibraryView":"cards","dateFormat":"dd-MM-yyyy","languages":[{"key":"es","label":"Español","default":true},{"key":"en","label":"English","default":false},{"key":"pt","label":"Português","default":false}]};
