// AUTO-GENERATED by scripts/render-doc-pages.cjs. Do not edit by hand.
// 24 pages from 8 real CEJIL filings, 3.1MB in public/doc-pages.
export interface DocPageAsset {
  file: string;
  originalName: string;
  kind: "cover" | "body" | "signatures";
  page: number;
  width: number;
  height: number;
  aspect: "portrait" | "landscape" | "square";
}

export const DOC_PAGE_BASE = "doc-pages";

export const docPageAssets: DocPageAsset[] = [
  {
    "file": "105647-cover.jpg",
    "originalName": "105647_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 935,
    "height": 1113,
    "aspect": "portrait"
  },
  {
    "file": "105647-body.jpg",
    "originalName": "105647_p5.jpg",
    "kind": "body",
    "page": 5,
    "width": 935,
    "height": 1110,
    "aspect": "portrait"
  },
  {
    "file": "105647-signatures.jpg",
    "originalName": "105647_p9.jpg",
    "kind": "signatures",
    "page": 9,
    "width": 935,
    "height": 1092,
    "aspect": "portrait"
  },
  {
    "file": "10958-cover.jpg",
    "originalName": "10958_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 935,
    "height": 953,
    "aspect": "square"
  },
  {
    "file": "10958-body.jpg",
    "originalName": "10958_p5.jpg",
    "kind": "body",
    "page": 5,
    "width": 935,
    "height": 1164,
    "aspect": "portrait"
  },
  {
    "file": "10958-signatures.jpg",
    "originalName": "10958_p10.jpg",
    "kind": "signatures",
    "page": 10,
    "width": 935,
    "height": 1164,
    "aspect": "portrait"
  },
  {
    "file": "11267-cover.jpg",
    "originalName": "11267_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 910,
    "height": 1136,
    "aspect": "portrait"
  },
  {
    "file": "11267-body.jpg",
    "originalName": "11267_p6.jpg",
    "kind": "body",
    "page": 6,
    "width": 910,
    "height": 1188,
    "aspect": "portrait"
  },
  {
    "file": "11267-signatures.jpg",
    "originalName": "11267_p12.jpg",
    "kind": "signatures",
    "page": 12,
    "width": 910,
    "height": 1188,
    "aspect": "portrait"
  },
  {
    "file": "11421-cover.jpg",
    "originalName": "11421_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 910,
    "height": 1114,
    "aspect": "portrait"
  },
  {
    "file": "11421-body.jpg",
    "originalName": "11421_p35.jpg",
    "kind": "body",
    "page": 35,
    "width": 910,
    "height": 1188,
    "aspect": "portrait"
  },
  {
    "file": "11421-signatures.jpg",
    "originalName": "11421_p70.jpg",
    "kind": "signatures",
    "page": 70,
    "width": 910,
    "height": 1188,
    "aspect": "portrait"
  },
  {
    "file": "11425-cover.jpg",
    "originalName": "11425_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 910,
    "height": 1135,
    "aspect": "portrait"
  },
  {
    "file": "11425-body.jpg",
    "originalName": "11425_p36.jpg",
    "kind": "body",
    "page": 36,
    "width": 910,
    "height": 1188,
    "aspect": "portrait"
  },
  {
    "file": "11425-signatures.jpg",
    "originalName": "11425_p71.jpg",
    "kind": "signatures",
    "page": 71,
    "width": 910,
    "height": 1188,
    "aspect": "portrait"
  },
  {
    "file": "12487-cover.jpg",
    "originalName": "12487_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 935,
    "height": 1111,
    "aspect": "portrait"
  },
  {
    "file": "12487-body.jpg",
    "originalName": "12487_p8.jpg",
    "kind": "body",
    "page": 8,
    "width": 935,
    "height": 1165,
    "aspect": "portrait"
  },
  {
    "file": "12487-signatures.jpg",
    "originalName": "12487_p16.jpg",
    "kind": "signatures",
    "page": 16,
    "width": 935,
    "height": 1109,
    "aspect": "portrait"
  },
  {
    "file": "148884163194-cover.jpg",
    "originalName": "148884163194_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 935,
    "height": 907,
    "aspect": "square"
  },
  {
    "file": "148884163194-body.jpg",
    "originalName": "148884163194_p4.jpg",
    "kind": "body",
    "page": 4,
    "width": 935,
    "height": 1165,
    "aspect": "portrait"
  },
  {
    "file": "148884163194-signatures.jpg",
    "originalName": "148884163194_p8.jpg",
    "kind": "signatures",
    "page": 8,
    "width": 935,
    "height": 1165,
    "aspect": "portrait"
  },
  {
    "file": "150428856654-cover.jpg",
    "originalName": "150428856654_p1.jpg",
    "kind": "cover",
    "page": 1,
    "width": 935,
    "height": 961,
    "aspect": "square"
  },
  {
    "file": "150428856654-body.jpg",
    "originalName": "150428856654_p49.jpg",
    "kind": "body",
    "page": 49,
    "width": 935,
    "height": 1164,
    "aspect": "portrait"
  },
  {
    "file": "150428856654-signatures.jpg",
    "originalName": "150428856654_p97.jpg",
    "kind": "signatures",
    "page": 97,
    "width": 935,
    "height": 1164,
    "aspect": "portrait"
  }
];
